### ISSUE TITLE
Feature Request: Generate compile_commands.json

### ISSUE THREAD

**Issue by Knowledge91** [platformio/platformio-core#2990]
I am using emacs with `lsp-mode` and *clangd* language server. For code completion the language server need an **compile_commands.json** file, which can be produced by cmake.
- [compile_commands.json definition](https://clang.llvm.org/docs/JSONCompilationDatabase.html)
- [How to produce compile_commands.json with cmake](https://clang.llvm.org/extra/clangd/Installation.html)

I would love to see a command similar to `pio init --ide emacs` that produces a compile_commands.json instead of a .clang_complete file, which I need for Intellisense.

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-core/commit/7a07a2e63eb51f8e403ecaf0fb2e4029d7b54744

Could you re-test with `pio upgrade --dev`?

**Comment by Knowledge91** [comment]
I did and noticed that you produce an additional .ccls file, which is used by the ccls language server. Unfortunately cland, the language server of the llvm developers, uses a ‘.compile_commands.json’ file

**Comment by ivankravets** [comment]
How are you going to use clang with `compile_commands.json` when it's not compatible with GCC flags and other architecture features? It will fail, just try it for AVR.

**Comment by Knowledge91** [comment]
Haha. Actually I just want the intellisense to work with cland. For compilation I just the pio pipeline.

**Comment by ivankravets** [comment]
Yes, but clang C/C++ Preprocessor will not understand your GCC code. You actually need clang_complete and we generate it https://github.com/platformio/platformio-core/blob/develop/platformio/ide/tpls/emacs/.clang_complete.tpl

**Comment by Knowledge91** [comment]
You don’t get me. The .clang_complete file is not read by the cland language server, which is the default language server for the emacs lsp-mode. It’s like the .ccls file for the ccls language server 😉
Anyways thanks for your quick responses. Keep up the good work.

**Comment by mnrce** [comment]
@ivankravets:
Hi, can this issue be re-opened?
Each C++ language servers support its own compile-flag file: 
- For `ccls`, it is [.ccls](https://github.com/MaskRay/ccls/wiki/Project-Setup#ccls-file) (which PIO generates)
- For `clangd`, it is [compile_flags.txt](https://clang.llvm.org/extra/clangd/Installation.html#compile-flags-txt)
- For `cquery`, it is [.cquery](https://github.com/cquery-project/cquery/wiki/.cquery)

But all of them support `compile_commands.json` ([ccls](https://github.com/MaskRay/ccls/wiki/Project-Setup#compile_commandsjson), [clangd](https://clang.llvm.org/extra/clangd/Installation.html#compile-commands-json), [cquery](https://github.com/cquery-project/cquery/wiki/Compilation-database#compile_commandsjson)) , so if you can generate `compile_commands.json`, we can use PIO with any cpp lsp we want, instead of generating `.ccls` file which only works for `ccls`.

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`

See docs https://docs.platformio.org/en/latest/faq.html#compilation-database-compile-commands-json
