### ISSUE TITLE
Add support for TI SimpleLink platform (CC3200 Launchpad board)

### ISSUE THREAD

**Issue by berezovskyi** [platformio/platformio-core#323]
Hi,

I would love to see CC3200 Launchpad supported by PlatformIO!

I looked through the `platforms` and `boards`directories in the source tree and new work seems to consist only of crafting proper JSON files? If it is so, I could try doing it myself initially.

Did you have a chance to work with the SimpleLink platform before?

**Comment by ivankravets** [comment]
Hi,

> I looked through the platforms and boards directories in the source tree and new work seems to consist only of crafting proper JSON files? If it is so, I could try doing it myself initially.

No, need to create separate platform `tisimplelink`. The required core files are located in http://energia.nu application, called Energia. Also, need to create own build script and etc. If you are interested in it and want help us, I would be thankful.

> Did you have a chance to work with the SimpleLink platform before?

Yes, we have tried to work with TI CC2538DK and TI CC2650DK for @SmartAnthill project. Nevertheless, we didn't use PlatformIO because it was only research.

**Comment by berezovskyi** [comment]
Hi Ivan, sorry for the late answer, the focus in my thesis got shifted to other tasks, but I will see if have the time to look into it afterward. Thank you for the pointers as to where to look. Best of luck to PlatformIO!

**Comment by ivankravets** [comment]
Hey @berezovskyi,

Good luck with your thesis :+1: 

P.S: Don't forget about PlatformIO :blush:

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-titiva/issues/1
