### ISSUE TITLE
Connection Error accessing api.platformio.org

### ISSUE THREAD

**Issue by jacklunn** [platformio/platformio-core#3314]
### Configuration

**Operating system**: MacOS Catalina 10.15

**PlatformIO Version** (`platformio --version`): PlatformIO, version 4.1.0

### Description of problem

I'm trying to initialize a new project but the ide hangs.  I dropped to the command line and it looks like api.platformio.org isn't reachable...

#### Steps to Reproduce

from the command line:

% pio boards
[API] ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')) (incremented retry: max=5, total=1)

**Comment by daveschafer** [comment]
Same problem here, it seems like the servers are down?

`[API] ConnectionError: HTTPConnectionPool(host='api.platformio.org', port=80): Max retries exceeded with url: /v2/lib/search?query=name%3A%22AsyncTCP-esphome%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0f73bf3cc0>: Failed to establish a new connection: [Errno 110] Connection timed out',)) (incremented retry: max=5, total=1)`

**Comment by krupaldesai** [comment]
Yup, even website seems down `https://platformio.org/` :(

**Comment by fabitom** [comment]
Yup, can't install libraries. Any way to install from mirror or github ?

**Comment by tita1705** [comment]
[Documentation website](http://docs.platformio.org/en/latest) is working

**Comment by pipe89** [comment]
It's now up and running.

**Comment by lukasz-gieraltowski** [comment]
I still have a problem with other calls like `pio account show` (version 4.1.0)

```PIO Plus (https://pioplus.com) v2.6.1
Error: [API] Invalid response: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>```

It looks like a server outage. Looking at the tickets I see, it's not the first time. Maybe it would be a good idea to implement some kind of status page?

**Comment by ivankravets** [comment]
Sorry for the issue. This is actually the 2nd time this year. The first was caused by planned maintenance.
Yesterday's issue was caused by our Ukrainian's dedicated server (E1410 System Fatal error). We fixed it by removing 2 banks of RAM. Let's see how will it work next week. If we have a problem again, we will move to VPS or cloud instance.

**Comment by wilmardo** [comment]
@ivankravets This issue seems back again :)

Is there a statuspage for the API? Might be a good idea to mitigate future questions like this. There is statuspage.io, also an opensource alternative:
https://github.com/CachetHQ/Cachet

**Comment by bramschats** [comment]
Same problem here.

**Comment by ivankravets** [comment]
It should work now. Sorry for the issue.

**Comment by olssondaniel1983** [comment]
Still getting 502

**Comment by ivankravets** [comment]
All services are restored, including PIO Plus.

Again, sorry for the isues.

Happy New Year and happy coding with PlatformIO! 😊
