### ISSUE TITLE
pre_and_post_hooks are not called if a build fails

### ISSUE THREAD

**Issue by akosfonod** [platformio/platformio-core#3698]
Hi,

I just noticed if a build fails, then the post-build scrip(s) are not called.
I am using the pre and post sripts to ingest git commit id into my binaries.

Pre step: ingest commit id into a header template
--Build--
Post step: restore the template.

This behavior might be intentional, but might be good to add an extra hook stg like: final:final_script.

Similar to the "try,catch,finally"

Cheers!

**Comment by sethfischer** [comment]
If your use case permits you may want to consider using environment variables to achieve your goal (rather than modifying a template).

The following example uses dynamic build flags as described in the [Advanced Scripting](https://docs.platformio.org/en/latest/projectconf/advanced_scripting.html) section of the PlatformIO documentation.

```ini
; platformio.ini
[common]
build_flags =
    !python3 define-git-revision.py
```

```python
#!/usr/bin/env python3
# define-git-revision.py

import subprocess

REVISION = subprocess.check_output(["git", "rev-parse", "HEAD"]).strip()

print("-D SRC_REVISION='\"{}\"'".format(REVISION.decode("UTF-8")))
```

```cpp
// src/main.cpp

#ifndef SRC_REVISION
#define SRC_REVISION "(revision not defined)"
#endif

void loop()
{
    Serial.println(SRC_REVISION);
}
```
