### ISSUE TITLE
Updating platforms

### ISSUE THREAD

**Issue by hcccs** [platformio/platformio-core#4143]
I'm trying to update my platform Expressif 32 from version 3.2.0 to 3.4.0 but it keeps spinning and nothing happens. What's wrong?

**Comment by ivankravets** [comment]
It seems you need to wait while PlatformIO finishes upgrading. Otherwise, you can update the dev-platform from the CLI with a progress. See:

- https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli
- https://docs.platformio.org/en/latest/core/userguide/cmd_update.html
