### ISSUE TITLE
Not being able to find a package should result in error, not warning

### ISSUE THREAD

**Issue by MacDada** [platformio/platformio-core#4484]
```ini
lib_deps =
    foobarbaz
```

```
✗ pio run
[…]
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing foobarbaz
Warning! Could not find the package with 'foobarbaz' requirements for your system 'darwin_x86_64'
```

I believe it does not make sense to just warn me about that – if I require a lib and it does not exist, my code will not work anyway –> as soon as I try to `#include` the lib in the code. So, better to know sooner than later.

Use case scenario:

1. I configure `lib_deps` to fetch the lib package.
2. I build -> it succeeds! [I don't notice the warning]
3. I write code that is using the lib.
4. I build -> It fails, because lib not found [and now I'm searching for reason…].

**Comment by ivankravets** [comment]
This is the legacy dependency declaration and PlatformIO Core treats it as a "built-in" library. We don't do a "deep search" for built-in libraries because they depend on the project framework.

Please check the valid specifications https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_install.html#package-specifications
