### ISSUE TITLE
udev rules warning even after following procedure to install them.

### ISSUE THREAD

**Issue by iplayfast** [platformio/platformio-core#4538]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [x] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

**PlatformIO Version** (`platformio --version`):

#### Steps to Reproduce

1.
2.
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by iplayfast** [comment]
The 
Warning! Your `/etc/udev/rules.d/99-platformio-udev.rules` are outdated. Please update or reinstall them.
More details: https://docs.platformio.org/en/latest/core/installation/udev-rules.html
warning seems to be triggered by this section.
https://github.com/platformio/platformio-core/blob/bd3b29c304cdd01482aea8d2d161a465dcfd6cec/platformio/util.py#L481-L509

I could be wrong but it's looking for the rules in both places(etc/udev and lib/udev) , but the instructions say to put them in etc/udev only. 

In anycase, I'm getting this warning even after I follow the instructions on updating them.

**Comment by iplayfast** [comment]
ls -lh /etc/udev/rules.d/99-platformio-udev.rules 
-rw-r--r-- 1 root root 8.1K Feb  2 03:27 /etc/udev/rules.d/99-platformio-udev.rules

**Comment by maxgerhardt** [comment]
And what's `sha256sum /etc/udev/rules.d/99-platformio-udev.rules`? Is it `4135E1B85D68928DACB876023F0B11A1A16F675EBD36FA7D677867A821D6247E` (lower or uppercase doesn't matter)

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by islamelnabarawy** [comment]
For anyone running into the same issue, it's caused by the fact that the instructions in the documentation lead you to download that file from the `develop` branch regardless of which version of PlatformIO you're actually on:

https://github.com/platformio/platformio-docs/blob/develop/core/installation/udev-rules.rst?plain=1#L30-L34

To fix this, you can replace `develop` in the download command with the exact version number you're on. For example, here is what it would look like for the current stable version, 6.1.14:
```
curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core/v6.1.14/platformio/assets/system/99-platformio-udev.rules | sudo tee /etc/udev/rules.d/99-platformio-udev.rules
```

You can figure out the version you are currently on by running `pio --version` or going to your PlatformIO Home and checking the version number under the logo.

If you prefer to download the file from the browser directly, you can go to the file on Github:
> https://github.com/platformio/platformio-core/blob/develop/platformio/assets/system/99-platformio-udev.rules

then select the version you are currently running from the left-side menu under `Tags`, download the raw file and put it in your `/etc/udev/rules.d/` folder.

Don't forget to follow the rest of the instructions [in the documentation](https://docs.platformio.org/en/stable/core/installation/udev-rules.html) after updating your file. You still need to restart `udev` and make sure your user has the right groups.
