### ISSUE TITLE
Board Farm: run tests on all targets?

### ISSUE THREAD

**Issue by peterus** [platformio/platformio-core#4549]
Question to "Board Farm" in [documentation](https://docs.platformio.org/en/latest/plus/pio-remote.html).

I was reading this text:

> You connect these devices via USB hub to PC and instruct PlatformIO Remote Development Solution to process your test on ALL targets connected to a specific agent.

But I can not find this part in the documentation. Can you guide me to it? Or is this not implemented? I think I was reading about it somewhere else.

**Comment by ivankravets** [comment]
Do you mean https://docs.platformio.org/en/latest/core/userguide/remote/cmd_test.html ?

**Comment by peterus** [comment]
I know the remote documentation, but I am missing the part do dispatch to ALL connected devices. currently I have to find out which ttyUSB's are available and which boards are attached to it.
Is there an simpler way than just guessing the tty's?

**Comment by ivankravets** [comment]
If you have multiple boards connected to the host machine and they have the same PID/VID, the only solution is to parse `pio remote device list` and then `pio remote test --upload-port value`.

Please note that you can also run CI runner (Github, Gitlab, etc) on your host machine and use `pio test` instead of `pio remote test`. It will give you more control over the unit testing.

**Comment by ivankravets** [comment]
Please reopen if you still need help
